version: '3'

tasks:
  client:
    dir: client
    cmds:
      - npm run build
      
  admin_build:
    dir: admin
    cmds:
      - npm run build

  login_build:
    dir: login
    cmds:
      - npm run build

      
  admin:
    deps: [admin_build]
    cmds:
      - sed -i 's/static\/js\//static\/adminjs\//g' admin/build/index.html
      - sed -i 's/static\/css\//static\/admincss\//g' admin/build/index.html
    silent: true

  login:
    deps: [login_build]
    cmds:
      - sed -i 's/static\/js\//static\/loginjs\//g' login/build/index.html
      - sed -i 's/static\/css\//static\/logincss\//g' login/build/index.html
    silent: true

  all:
    deps: [client, admin, login]

  admin_update:
    dir: admin
    cmds:
      - npm update
      
  client_update:
    dir:
      client
    cmds:
      - npm update
      
  up:
    deps: [admin_update, client_update]

  build:
    cmds:
      - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -tags netgo -ldflags '-w -X main.version={{.GIT_TAG}}' -o emperor
    vars:
      GIT_TAG:
        sh: git describe --tags
    
  deploy:
    deps: [build]
    cmds:
      - rsync -avzz emperor web emperor:emperor/
      - ssh auspicious systemctl restart emperor.service
